# Generated by Django 5.1.6 on 2025-02-18 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "place",
                    models.CharField(
                        help_text="Укажите место, где будете выполнять привычку", max_length=150, verbose_name="Место"
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        default="00:00",
                        help_text="Укажите время, в которое будете выполнять привычку",
                        verbose_name="Время",
                    ),
                ),
                ("action", models.CharField(help_text="Укажите действие", max_length=150, verbose_name="Действие")),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Поставьте галочку, если это приятная привычка",
                        verbose_name="Признак полезной привычки",
                    ),
                ),
                (
                    "periodic",
                    models.IntegerField(
                        default=1,
                        help_text="Укажите, сколько раз в неделю вы будете выполнять привычку",
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "award",
                    models.CharField(
                        blank=True,
                        help_text="Укажите, чем вы себя вознаградите",
                        max_length=250,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "duration",
                    models.TimeField(
                        default="00:02",
                        help_text="Укажите длительность выполнения привычки",
                        verbose_name="Длительность",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Поставьте галочку, если хотите, чтобы эту привычку видели все",
                        verbose_name="Признак публичности",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
                (
                    "related_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите связанную привычку",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_habit",
                        to="habit_tracker.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "привычка",
                "verbose_name_plural": "привычки",
            },
        ),
    ]
