# Generated by Django 5.1.6 on 2025-02-18 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="duration",
            field=models.DurationField(
                default=datetime.timedelta(seconds=120),
                help_text="Укажите длительность выполнения привычки",
                verbose_name="Длительность",
            ),
        ),
    ]
